# Generated by Django 3.2.9 on 2022-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_mylinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylinks',
            options={'ordering': ['-created'], 'verbose_name': 'мои ссылку', 'verbose_name_plural': 'ссылки'},
        ),
        migrations.AddField(
            model_name='mylinks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000'),
            preserve_default=False,
        ),
    ]
