# Generated by Django 3.2.9 on 2022-06-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220603_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylinks',
            options={'get_latest_by': ['created'], 'ordering': ['-created'], 'verbose_name': 'мои ссылку', 'verbose_name_plural': 'ссылки'},
        ),
    ]
